version: '3'
services:
  activemq:
    container_name: activemq
    image: bobcrutchley/activemq
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
  babyapi:
    container_name: babyapi
    build:
      context: BabyNameAPI
      args:
      - artifact_id=BabyNameAPI
      - version=0.0.1-SNAPSHOT
    ports:
    - 8080:8080
  babyconsumer:
    container_name: babyconsumer
    build:
      context: BabyNameConsumer
      args:
      - artifact_id=BabyNameConsumer
      - version=0.0.1-SNAPSHOT
  babygenerator:
    container_name: babygenerator
    build:
      context: BabyNameGeneratorAPI
      args:
      - artifact_id=BabyNameGenerator
      - version=0.0.1.SNAPSHOT